Add folder for Computational mathematics. Add folder for second homework in CM. Add universal programm for second homework in CM
Contributors-pi8/pi8-spbstu-labs pull request #18
Opened 2024-10-16 16:20 UTC by User1235321

P.s насколько я знаю нельзя залить пустую папку, поэтому такое длинное описание pr

2024-10-16 17:22 UTC, imKamikoto commented
слишком длинное название коммита. так же, не стоит писать в названии, какая папка была добавлена и т.д.  просто "Added CM homework #(2 как пример)"

2024-10-16 17:23 UTC, SlivkaSadovka requested changes
Все перенести в папку со своим ФИО

2024-10-16 17:25 UTC, imKamikoto commented
сделать такую структуру: Computational_mathematics/homework_2/имя.фамилия/.....

2024-10-16 17:28 UTC, imKamikoto commented on Computational_mathematics/homework_2/guide.txt
мы используем .md

2024-10-16 22:04 UTC, SlivkaSadovka approved these changes

2024-10-17 03:13 UTC, imKamikoto approved these changes
красота

2024-10-17 07:06 UTC, SlivkaSadovka approved these changes

2024-10-17 07:07 UTC, merged