Update repository and add some automation
Contributors-pi8/pi8-spbstu-labs pull request #31
Opened 2024-10-18 23:24 UTC by AlexZagric

Предлагаю некоторые изменения в репозитории:
- Небольшое изменение в README.md репозитория:
   - Добавил пару виджетов, чтобы не было так грустно 
   - Перенес требования к участию в разработке в CONTRIBUTING.md
- Добавил GitHub Actions для компиляции Java работ с помощью Gradle
- Как предлагалось в #17 добавил автоматизацию для ярлыков. Они автоматически выставляются при изменениях в нужных папках

Так как я не знаю всех ваших требований к оформлению жду любую критику и предложения про то, что можно добавить в CONTRIBUTING.md. Да и по поводу других изменений тоже.

2024-10-19 01:07 UTC, StantStantov requested changes
Все очень хорошо, нужно просто чуть-чуть подправить

2024-10-19 01:07 UTC, StantStantov commented on README.md
> +  ![Java](https://img.shields.io/badge/java-%23ED8B00.svg?style=for-the-badge&logo=openjdk&logoColor=white)
Выглядит неплохо, но, как-по мне, лишнее.

2024-10-19 01:07 UTC, StantStantov commented on README.md
> +[![Stargazers over time](https://starchart.cc/Contributors-pi8/pi8-spbstu-labs.svg?variant=adaptive)](https://starchart.cc/Contributors-pi8/pi8-spbstu-labs)
Тоже неплохо, но на телефоне выглядит очень плохо. Имена накладываются друг на друга и все превращается в кашу.

Да и, честно говоря, не вижу в этом особого смысла.

2024-10-19 01:07 UTC, StantStantov commented on README.md
> +  <h3>СПбПУ ─ Программная инжинерия ─ Группа №8</h3>
Инженерия, не инжинерия

2024-10-19 08:18 UTC, imKamikoto commented
для чего проверка на компилируемость java работ?

2024-10-19 09:03 UTC, SlivkaSadovka commented
> для чего проверка на компилируемость java работ? 
> все остальное хорошо 

А мне кажется, что неплохая идея. Чтоб код был рабочий

2024-10-19 13:26 UTC, SlivkaSadovka approved these changes
Подправить грамматическую ошибку и нормально. Мне кажется, что все остальное выглядит очень хорошо. Оформление классное, тесты будут кстати. Я за

2024-10-19 13:27 UTC, AlexZagric commented
> Подправить грамматическую ошибку и нормально. 

Да, попозже исправлю, когда доползу до компа.

2024-10-19 13:28 UTC, SlivkaSadovka commented
> > Подправить грамматическую ошибку и нормально.
>

Ну и список всех, кто поставил звездочки с графиком тоже бы убрать. Выглядит действительно лишним

2024-10-19 16:17 UTC, iamneefee commented on README.md
> -  <br />
Эти виджеты можно было и оставить, мне кажется

2024-10-19 16:17 UTC, iamneefee approved these changes

2024-10-19 16:18 UTC, AlexZagric commented on README.md
> -  <br />
Попросили убрать, я бы оставил

2024-10-19 16:29 UTC, SlivkaSadovka commented on README.md
> -  <br />
не нужоны нам эти вижеты ваши
![image](https://github.com/user-attachments/assets/9635f6c6-c364-4844-b202-7bc4403f6c90)

2024-10-20 04:14 UTC, StantStantov approved these changes
Все очень хорошо

2024-10-20 07:16 UTC, merged