БЖД lab_8
Contributors-pi8/pi8-spbstu-labs pull request #41
Opened 2024-10-31 20:33 UTC by dr0nych2

2024-10-31 20:36 UTC, SlivkaSadovka approved these changes
БЖД нельзя никак адекватно перевести на английский, чтоб не выглядело глупо, поэтому решили на русском ебануть название папки. 
Я считаю нормально

2024-10-31 20:45 UTC, imKamikoto commented
> БЖД нельзя никак адекватно перевести на английский, чтоб не выглядело глупо, поэтому решили на русском ебануть название папки. 
> 
> Я считаю нормально

life safety

2024-10-31 20:47 UTC, SlivkaSadovka commented
> life safety

И все равно звучит так себе. Впрочем, это мое мнение 🤷‍♂️

2024-10-31 20:50 UTC, imKamikoto commented
> > life safety
> 
> И все равно звучит так себе. Впрочем, это мое мнение 🤷‍♂️

тогда нарушается правило репы. бтв смотрите сами, я просто предложил

2024-10-31 20:50 UTC, imKamikoto approved these changes

2024-10-31 20:53 UTC, AlexZagric reviewed
Папку лучше не использовать кириллицу в названии папок и тем более в названии веток. Кто знает, к чему это приведет:
![image](https://github.com/user-attachments/assets/ca50d007-0e29-4a9a-a6d5-866eaa4eb325)

2024-10-31 21:13 UTC, dr0nych2 commented
> Папку лучше не использовать кириллицу в названии папок и тем более в названии веток. Кто знает, к чему это приведет:
> ![image](https://github.com/user-attachments/assets/ca50d007-0e29-4a9a-a6d5-866eaa4eb325)
> 

Все вопросы к Роману

2024-11-01 12:11 UTC, StantStantov commented
БЖД на английском - EHS - Environment Health and Safety

2024-11-01 12:11 UTC, StantStantov requested changes
Поменяйте название папки

2024-11-14 10:46 UTC, closed without merging