Microelectronics lab 4
Contributors-pi8/pi8-spbstu-labs pull request #42
Opened 2024-10-31 20:36 UTC by AlexZagric

2024-10-31 20:46 UTC, imKamikoto requested changes
зачем .bdf файлы?

2024-10-31 20:50 UTC, AlexZagric commented
> зачем .bdf файлы?

Было решено https://github.com/Contributors-pi8/pi8-spbstu-labs/pull/26#issuecomment-2422281642 оставлять их в src папке.

2024-10-31 20:52 UTC, imKamikoto commented
> > зачем .bdf файлы?
> 
> Было решено [#26 (comment)](https://github.com/Contributors-pi8/pi8-spbstu-labs/pull/26#issuecomment-2422281642) оставлять их в src папке.

с телефона смотрел, не увидел src. извиняюсь!

2024-10-31 20:52 UTC, imKamikoto approved these changes

2024-11-01 12:23 UTC, iamneefee approved these changes

2024-11-01 12:23 UTC, merged